title: "Saul Montes De Oca"
email: a01025975@itesm.mx
description: 
  This is my Major League Hacking Fellowship portfolio. Take a look to the awesome projects a worked on during this explorer internship.
baseurl: "/" 
url: "/portfolio-template" 
twitter_username: SaulMontesDeO10 
github_username:  saulmontesdeoca

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
theme: jekyll-theme-cayman